{
 "title": "disk status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ram Using",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "informacion_pc",
     "rawSql": "SELECT 'Total' AS metric, ramT AS value\nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa)\nUNION ALL\nSELECT 'Libre' AS metric, ramL AS value\nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa)\nUNION ALL\nSELECT 'Usado' AS metric, RAMU AS value\nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa);\n\n"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "informacion_pc",
     "rawSql": "SELECT 'Total' AS metric, disckT AS value \nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa)\nUNION ALL\nSELECT 'Libre' AS metric, disckL AS value \nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa)\nUNION ALL\nSELECT 'Usado' AS metric, disckU AS value \nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa);\n"
    }
   ]
  },
  {
   "title": "cpu Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "informacion_pc",
     "rawSql": "SELECT cpu AS cpu \nFROM psa\nWHERE id = (SELECT MAX(id) FROM psa);\n"
    }
   ]
  }
 ]
}